### ISSUE TITLE
UpdateUser scenario

### ISSUE THREAD

**Issue by alireza267** [aguacongas/Identity.Redis#2]
I've got some problem with UpdateAsync method. 
when I Update my user by calling:
### usermanager.UpdateAsync()
new properties of user stores in redis except the value of ConcurrencyStamp. so subsequent UpdateAsync requests fail because of inequality of ConcurrencyStamp property of users  and users-concurency value. 
how shall i fix that?

**Comment by aguacongas** [comment]
Can you provide a repro code ?  
What's version do you use ?

**Comment by alireza267** [comment]
Thanks for your response @aguacongas ,
I'm using version 1.1.1
my problem is very simple, I'm using a UserManager on top of  Identity.Redis and somewhere in my code I get user by:
`var appUser = _userManager.FindByNameAsync(userName);`
after some change in my appUser:
`appUser.property1 = "hello"`
I would like to save my edited appUser:
`var result = await _userManager.UpdateAsync(appUser);`
everything is fine for the first update, If I want to UpdateAsync one more time  I'm receiving a concurrencyFailure error.
I think this is a bug in UpdateAsync implementation.

**Comment by aguacongas** [comment]
Did you try your scenerio using EF Core stores ?

**Comment by alireza267** [comment]
Thank you very much dear @aguacongas ,
I wrote a same test and saw that everything works perfect. so I reviewed my code and I realize that somewhere else in my code I got this user(user1) and update it too, so concurrency stamp changes in two section!
This make me search on what concurrency stamp does and find that it prevents concurrency update conflict. that is the answer.
